# Site settings
title: AKASHA blog
email: hello@akasha.world
logo: logo.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
description: > # this means to ignore newlines until "url:"
  AKASHA | The language of freedom | A Next-Generation Social Blogging Network.
url: "http://akasha.world"

baseurl: ""
twitter_username: AkashaProject
github_username:  AkashaProject

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
